### ISSUE TITLE
Test for UM Activation is no longer correct

### ISSUE THREAD

**Issue by pattyok** [yaronguez/um-resend-activation-form#1]
I updated to the latest version of UM (2.0.17) and the test you are using to see if UM is activated is no longer working. Even though UM is installed, I am getting the UM is not installed error.

**Comment by lramos2017** [comment]
Hi all,
I've forked this plugin to work with UM2.0. Can't upload the files for some reason. Let me know if you want it.

**Comment by yaronguez** [comment]
Great! Sure, feel free to submit a pull request and i'll review / approve.

Thanks!

**Comment by vijayhardaha** [comment]
If you'll see the file `public/class-um-raf-public.php`

inside function `output_form()` you'll see class checking code.

```php
if(!class_exists('UM_API')){
    return apply_filters('um_raf_no_um_message', __('The plugin Ultimate Member is required and not currently installed.','um_raf'));
}
```

change `UM_API` to `UM` only. it will start working.

This add on plugin need to fix this update issue.

**Comment by jppluymers** [comment]
Hello

I'm using Ultimate member v.2.1.5 and Wordpress v5.4
To my regret, your wonderfull plugin doesn't work: Clicking on the Resend button results in a loop and nothing happens anymore. I also have an error from Wordpress in my page where a put in the shortcode. Error message: Warning: Illegal string offset 'title' in /home/websitename/public_html/wpjp2/wp-content/plugins/ultimate-member/includes/admin/core/class-admin-columns.php on line 239
— UM R
Is there a possibility check what causes the loop and the error? Would you be so kind to update your plugin? Thank you so much!

![Afbeelding 21](https://user-images.githubusercontent.com/63521679/79620197-6b206880-810f-11ea-8d19-8cae4ce124e2.png)

**Comment by vijayhardaha** [comment]
@jppluymers 
I've fixed the error and did some minor fixes as well. Please try the v1.0.2 from the release.

I looked for Warning error but I didn't see any during my tests. Please try this new code and let me know if you still see the Warning error.

Thanks

**Comment by yaronguez** [comment]
@vijayhardaha I added you as a contributor so you can merge the PRs yourself.  Thanks for contributing!

**Comment by vijayhardaha** [comment]
@yaronguez Thanks
